### PR TITLE
iiit_allahabad_campus.md added

### PR DESCRIPTION
**Pull request by Athting**
Issue : #7

### CODE REVIEW

**Comment by Athting** [comment]
Issue : #2

**Comment by Athting** [comment]
Is there any issue please let me know.

**Comment by saumyacoder1709** [comment]
First of all make your repo up to date with the real repo. Then, create a .md file only in the branch "College" and not the jpg image. The .md file must contain the jpg image. name the .md file as rolno.md

**Comment by saumyacoder1709** [comment]
Generate a new PR with the changes I mentioned.

**Pull request closed without merging**
